channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.10
  - anndata=0.8.0
  - harmonypy
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - numpy
  - pandas=1.4.4
  - plotly
  - scanpy=1.9.1
  - pip
  - pip:
     - "--editable=git+https://github.com/Arcadia-Science/arcadia-pycolor.git#egg=arcadia_pycolor"
