# mkdocs.yml
site_name: Glial Origins

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - About BioFile Handling: BioFile_README.md
  - BioFile Usage: biofile_doc.md
  - String Functions Usage: string_functions_doc.md
  - Scanpy Wrappers Usage: scanpy_wrappers_doc.md