# mkdocs.yml
site_name: Glial Origins

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings:
      default_handler: python

nav:
  - index.md: Home
  - BioFile_README.md: About BioFile Handling
  - biofile_doc.md: BioFile Usage
  - string_functions_doc.md: String Functions Usage
  - scanpy_wrappers_doc.md: Scanpy Wrappers Usage