channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - orthofinder=2.5.4
  - transdecoder=5.5.0
  - bedtools=2.30.0
  - htop=3.2.1
  - bedops=2.4.41
  - pandas=1.4.3
  - scanpy=1.3.7
  - dask=0.15.2
  - leidenalg=0.8.10
  - cufflinks-py=0.17.0
  - scanorama=1.7.1
